services:
  gateway:
    build:
      context: ./gateway

  frontend:
    build:
      context: ..
      dockerfile: gchmis-openmrs-refapp/frontend/Dockerfile.dev

  backend:
    build:
      context: .

  db:
    ports:
      - "3307:3306"
